# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormMain(object):
    def setupUi(self, FormMain):
        FormMain.setObjectName("FormMain")
        FormMain.resize(900, 550)
        FormMain.setBaseSize(QtCore.QSize(900, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/.ico/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormMain.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(FormMain)
        self.frame.setGeometry(QtCore.QRect(0, 0, 900, 40))
        self.frame.setBaseSize(QtCore.QSize(900, 40))
        self.frame.setStyleSheet("background-color: blue;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(FormMain)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 901, 511))
        self.frame_2.setStyleSheet("background-color: skyblue;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.retranslateUi(FormMain)
        QtCore.QMetaObject.connectSlotsByName(FormMain)

    def retranslateUi(self, FormMain):
        _translate = QtCore.QCoreApplication.translate
        FormMain.setWindowTitle(_translate("FormMain", "Plain Craft Launcher 2"))
import Images.img_rc_rc
